# Copyright (c) 2018 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: include scenarios/etcd.yml
  include: "{{ item }}"
  with_first_found:
    - "scenarios/etcd_{{ ansible_architecture }}.yml"
    - "scenarios/etcd.yml"
  when:
    - deploy_project != "gelato" 
    - db_driver == "etcd" and etcd_container_enabled == false

- name: include scenarios/container.yml
  include: scenarios/container.yml
  when:
    - deploy_project != "gelato" 
    - db_driver == "etcd" and etcd_container_enabled == true
