# Copyright 2019 The OpenSDS Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Dummy variable to avoid error because ansible does not recognize the
# file as a good configuration file when no variable in it.
dummy:

###########
# GENERAL #
###########

# Do you need to install or clean up telemetry tools?
enable_telemetry_tools: false

# Grafana Repository config
grafana_repositroy: "deb https://packages.grafana.com/oss/deb stable main"
grafana_gpg_key: https://packages.grafana.com/gpg.key

# Telementry configs to be updated in opensds.conf
prometheus_conf_home: /etc/prometheus/
prometheus_conf_file: prometheus.yml
prometheus_url: 'http://{{ host_ip }}:9090'
alertmgr_conf_home: /etc/alertmanager/
alertmgr_conf_file: alertmanager.yml
alertmgr_url: 'http://{{ host_ip }}:9093'
grafana_conf_home: /etc/grafana/
grafana_data_home: /var/lib/grafana
grafana_conf_file: grafana.ini
grafana_url: 'http://{{ host_ip }}:3000'
grafana_restart_cmd: grafana-server
conf_reload_url: /-/reload

prometheus_push_mechanism: 'NodeExporter'
prometheus_push_gateway_url: 'http://{{ host_ip }}:9091'
node_exporter_watch_folder: /root/prom_nodeexporter_folder/
lvm_exporter_port: '9601'
kafka_endpoint: '{{ host_ip }}:9092'
kafka_topic: metrics

telemetry_work_dir: /opt/opensds-telemetry-linux-amd64
