# This YAML file contains driver-registrar & csi driver nodeplugin API objects,
# which are necessary to run csi nodeplugin for soda.

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ template "csipluginNodeplugin.fullname" . }}
  labels:
    app: {{ template "csipluginNodeplugin.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "csipluginNodeplugin.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "csipluginNodeplugin.fullname" . }}
      labels:
        app: {{ template "csipluginNodeplugin.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccount: csi-nodeplugin-block
      # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi-sodaplugin-block/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: {{ template "csipluginNodeplugin.fullname" . }}
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ .Values.image }}
          args :
            - "--csiEndpoint=$(CSI_ENDPOINT)"
            - "--sodaEndpoint=$(soda_ENDPOINT)"
            - "--sodaAuthStrategy=$(soda_AUTH_STRATEGY)"
            - "--v=8"
          env:
            - name: CSI_ENDPOINT
              value: unix://var/lib/kubelet/plugins/csi-sodaplugin-block/csi.sock
            - name: soda_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: sodaendpoint
            - name: soda_AUTH_STRATEGY
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: sodaauthstrategy
            - name: OS_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: osauthurl
            - name: OS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: osusername
            - name: OS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: ospassword
            - name: PASSWORD_ENCRYPTER
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: passwordencrypter
            - name: ENABLE_ENCRYPTED
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: enableEncrypted
            - name: OS_TENANT_NAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: ostenantname
            - name: PASSWORD_ENCRYPTER
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: passwordencrypter
            - name: ENABLE_ENCRYPTED
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: enableEncrypted
            - name: OS_PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: osprojectname
            - name: OS_USER_DOMAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: csi-configmap-sodaplugin-block
                  key: osuserdomainid
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/csi-sodaplugin-block
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: volume-devices-dir
              mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices
              mountPropagation: "Bidirectional"
            - name: pods-probe-dir
              mountPath: /dev
              mountPropagation: "HostToContainer"
            - name: iscsi-dir
              mountPath: /etc/iscsi/
            - name: ceph-dir
              mountPath: /etc/ceph/
            - name: certificate-path
              mountPath: /opt/soda-security
            - name: hosts
              mountPath: /etc
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-sodaplugin-block
            type: DirectoryOrCreate
        - name: volume-devices-dir
          hostPath:
            path: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: pods-probe-dir
          hostPath:
            path: /dev
            type: Directory
        - name: iscsi-dir
          hostPath:
            path: /etc/iscsi/
            type: Directory
        - name: ceph-dir
          hostPath:
            path: /etc/ceph/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
        - name: certificate-path
          hostPath:
            path: /opt/soda-security
            type: DirectoryOrCreate
        - name: hosts
          hostPath:
            path: /etc
            type: Directory
