# Default values for soda Service Broker
# Image to use
name: servicebroker
image:

  service-broker: sodafoundation/service-broker:v1.3.0

  etcd-store: quay.io/coreos/etcd:latest
# ImagePullPolicy; valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: IfNotPresent

# Specify if registering it when deploying the service broker
deployClusterServiceBroker: true

# Please modify these fields according to your real environment
sodaEndpoint: http://127.0.0.1:50040
sodaAuthStrategy: noauth
osAuthURL: http://127.0.0.1/identity
osUsername: admin
osPassword: soda@123
osTenantName: admin
osProjectName: admin
osUserDomainID: default
