# Default values for opensds csi plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image: opensdsio/csiplugin:latest
# ImagePullPolicy: valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: IfNotPresent
# ImageRestartPolicy: valid values are "Never", and "Always"
imageRestartPolicy: Never
# Please modify data fields in real environment
data:
  opensdsEndpoint: http://127.0.0.1:50040
  opensdsAuthStrategy: keystone
  osAuthURL: http://127.0.0.1/identity
  osUsername: admin
  osPassword: opensds@123
  osTenantName: admin
  osProjectName: admin
  osUserDomainId: default
  passwordEncrypter: aes
  enableEncrypted: F
