# Copyright 2019 The soda Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- set_fact:
    go_path: "{{ lookup('env', 'GOPATH') }}"

- name: check go_path
  shell: "{{ item }}"
  with_items:
    - echo "The environment variable GOPATH must be set and cannot be an empty string!"
    - /bin/false
  when: go_path == ""

- name: check for sushi source code existed
  stat:
    path: "{{ go_path }}/src/github.com/soda/nbp"
  register: sushiexisted

- name: download sushi source code if not exists
  git:
    repo: "{{ sushi_remote_url }}"
    dest: "{{ go_path }}/src/github.com/soda/nbp"
    version: "{{ sushi_repo_branch }}"
  when:
    - sushiexisted.stat.exists is undefined or sushiexisted.stat.exists == false

- name: build sushi binary file
  shell: make
  environment:
    GOPATH: "{{ go_path }}"
  args:
    chdir: "{{ go_path }}/src/github.com/soda/nbp"

- name: create sushi install directory if it doesn't exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ sushi_work_dir }}/csi"
    - "{{ sushi_work_dir }}/flexvolume"
    - "{{ sushi_work_dir }}/provisioner"

- name: copy sushi csi deploy scripts into sushi work directory
  copy:
    src: "{{ item }}"
    dest: "{{ sushi_work_dir }}/csi/"
    directory_mode: yes
  with_items:
    - "{{ go_path }}/src/github.com/soda/nbp/csi/deploy"
    - "{{ go_path }}/src/github.com/soda/nbp/csi/examples"

# flex volume support not available going forward
#- name: copy sushi flexvolume binary file into sushi work directory
#  copy:
#    src: "{{ go_path }}/src/github.com/soda/nbp/build/out/flexvolume.server.soda"
#    dest: "{{ sushi_work_dir }}/flexvolume/soda"
#    mode: 0755

- name: copy sushi provisioner deploy scripts into sushi work directory
  copy:
    src: "{{ item }}"
    dest: "{{ sushi_work_dir }}/provisioner/"
    directory_mode: yes
  with_items:
    - "{{ go_path }}/src/github.com/soda/nbp/soda-provisioner/deploy"
    - "{{ go_path }}/src/github.com/soda/nbp/soda-provisioner/examples"
